### ISSUE TITLE
Support for macOS?

### ISSUE THREAD

**Issue by arkdev9** [abhayram04/tars-att#2]
Would love to see it ported for Mac. Any plans to do so in the future?

**Comment by abhayram04** [comment]
We love the Mac. But we have found that majority of the educational institutions in our purview use Windows based PCs. So for now, the TARS attendance app will only be available on the Windows platform. If the situation does change, please do know that,  we're always ready to embrace the Mac :)
![love-mac](https://user-images.githubusercontent.com/16081413/77880589-9b948580-727a-11ea-832b-30f7df6356fa.gif)

**Comment by arkdev9** [comment]
Aw shucks, well that's a bummer. Still, I'll hope that changes some day!
